language: cpp
dist: xenial
notifications:
  - email: false

compiler:
  - gcc-7

install:
  - pip install --user conan
  - conan user # Automatic detection of arch, compiler, etc.

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CXX="g++-7"
        - CC="gcc-7"

before_script:
  - mkdir -p build
  - cd build
  - conan install -s cppstd=gnu17 -s build_type=Release --build=missing ..
  - cmake -DCMAKE_BUILD_TYPE=Release -S ..

script:
  - make && ctest --output-on-failure

