language: cpp
dist: xenial
notifications:
  - email: false

compiler:
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - boost1.68
      env:
        - CXX_COMPILER="g++-7"

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$CXX_COMPILER

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - make && ctest --output-on-failure

